>Name: bpRNA_RFAM_5770
UAUAAGUCCAAGGGGUGCCAAUUGGCUGAGAUGGUUUUAACCAAUCCCUUUGAACCUGAUCCGGUUAAUACCGGCGUAGGAAUGGAUUUUCUCUACAGC
.....(((((((((..((((())))).....(((((())))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5771
UUUAUCCACUAGGGGGGCCUAUUAUAGGCUGAGAUCAAAUGGGAAUUUGAGACUCUUAGUACCUGAUCUGGUUAAUGCCAGCGUAGGGAAGUGGAAAAGACAUUGC
.....(((((((((..(((((...))))).....((((((....))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5772
UAAGAUACCUCGGGGGGCCUGACAGGCUGAGAUGUGCGCGCACGGACCCGUUGAACCUGAACCGGUUAACACCGGCGGAGGGAAGGUCUGGAUACACCUC
.....(((((((((..(((((.))))).....(((((())))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5773
AUCUAUCCGUCGGGGUGCCCUAGGGGGCUGAGAGGUGCGUGCACCGACCCGUCGAACCUGAUCCGGGCAAUACCGGCGUAGGGAACGGGUAUCUUUGUGCA
.....(((((((((..(((((..))))).....(((((())))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5774
CGUUGUCGCUAGGGGUGCCCCCGUCAGGGGCUGAGAUGGCCGUGGACCGGCCAGACCCUUUGAACCUGAACCGGGUCAUACCGGCGGAGGGAAGCGGCGGGCGCUCCAA
.....(((((((((..(((((.....))))).....((((((.....))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5775
UUUUUUCACUAGGGGCGCCCGUACGGGCUGAGACAGAAUGGUUUCUGGACCCUUUGAACCUGAUCUGGAUUAUACCAGCGUAGGAAAGUGGGAAUGCAUGAAU
.....(((((((((..(((((..))))).....((((((..))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5776
UCAUGCAUGAGCCGGUGCCCAUUCUUCUCCCAUCAGCAUGGUCAGUUCAAACUGGUCGUGUUGAUGAUAGGGGGAUGUGGCUGAGAUUAUACGGCAAAACUUGAUCUGGAUAAUACCAGCGAAAGGAUCAUGUCAUCUCCCCUA
.....(((((((((..(((((.......................................................)))))..........))))....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5777
AGGCGUCACAAGAGGAGCUUUUGCUGAGAAUGACCUCCAGUUUUAAGUAAAUUCCAUAACAUUGGAGUUUUGCGCAAAGUCUGGGUGUCUAAACUCUUUGAACCUGAACAAGGUAAUGCUUGCGUAAGGGAUGUGCAGAAAUAAGUGG
.....(((((((((...(((.))).....((((((..................................................))))))..)))).....((((..((((......))))...))))..)))))............
>Name: bpRNA_RFAM_5778
CCGACUUAGUCGGGGUGCUGAUAACAGCUGAGAUAAUACCCGUGAACCUGAUACAGUUAAUACUGACGUAGGAAACUAAUGGUCUUACUCC
.....(((((((((..(((((..)))))..........))))....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5779
UGGAGGGGUACCGGGUGUACGAGGCAGAGUCCGGUCGUUCUGAGAUUAUACUGUCAUAACUUGAUCUAGAUAAUACUAGCGAAAGGACAUGCGUGGCAUUGAUU
.....(((((((((..(((((..............)))))..........)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5780
CAAAACCACUGGGGGAGCCUUUUAAAGGCUGAGAUUAAAGUGUACUACUUUAAGACCCUUUGAACCUGAUCUAGUUCAUACUAGCGGAGGGAAGUGUAGUCUGAAUGAU
.....(((((((((..(((((...))))).....((((((.......))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5781
CAAAAGCACCAGGGGUGCUUGAACCAGGAUAGCCUGCGAAAAGGCGGGCUAUCCGGGACCAGGCUGAGAAAGUCCCUUUGAACCUGAACAGGGUAAUGCCUGCGCAGGGAGUGUGCAGUUUUUUUUUU
.....(((((((((..(((((......................................))))).........)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5782
AAGUUGCACCAGGGGUGCCUGUAUUCUCAACGAUCUGAAGGCCUCUUGGCCUGGAUUGUUGUGAAUUGGGCUGAGAAAGUCCCUUUGAACCUGAACAGGAUAAUGCCUGCGAAGGGAGUGUGCAUUUCUACUUUU
.....(((((((((..(((((.............................................))))).........)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5783
GGGUACCCACGCGGGAGCGCAACGCCGAGUGCGCUGAGAGGACGGCUCGGGGCCGUCGACCGUACGAACCUGACCGGGUAAUGCCGGCGUAGGGAGUUGCAAAUGACCAUCA
.....(((((((((..(((((........))))).....(.((((.......)))))..)))).....((((.((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5784
GCACUUUAGUCGGGGUGCUUUGUAACCAAAUUGUACAAAGCUGAGAUGAUACCCGUGAACCUGAUACAGCUAACACUGACGUAGGAAACUAAUUAUGCCAAUAA
.....(((((((((..(((((...............)))))..........))))....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5785
GACUCUUAGUCGGGGUGCUAUUGCGUUAGCUGAGAUGAUACCCGUGAACCUGAUGCAGUUAAUACUGACGUAGGAAACUAGCAGUCAAUAUUG
.....(((((((((..(((((....)))))..........))))....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5786
AACAACCACUAGGGGUGCGUAAAGCUGAGAUUAACGACUGUUAGAUCCCUCUGACUCAAUCUAGGUAAUGCUAGCUGAUGGAAGUGGAAAUGAUAAUGG
.....(((((((((..(((().))).....((((((..))))))..))))....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5787
GCCAUUCACCAGGGGUGUCCCGUCAAGGGGCUGAGAUUCUGCUUUCAUGCGCAGUGACCCGUUGAACCUGAUCCAGUUCAUACUGGCGUAGGGACGGUGCAAAGACCUGAUG
.....(((((((((..(((((.....))))).....((((((......))))))...)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5788
AGCUCUUCCGAGGGGAGCACCAGACGGUGCUGAGAUGGUGGUGAACCGGACCCUUGAACCUGAUCCGGGUCAUGCCGGCGUAGGAACGGAACUGUCGUGCGCU
.....(((((((((..(((((....))))).....((((((.))))))..))))....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5789
CUCAAGUGCUAGGGGAGCCAAAAAUGGCUGAGAGGGGAUUCGUUCCCGACCCUUAGAACCUGACCAGGGUAAUGCCUGCGAAGGGAAGCACGUUUUACGAAAU
.....(((((((((..(((((..))))).....((((((..))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5790
CUCAAGUGCUAGGGGAGCCAGAAAUGGCUGAGAGGGGAUUCGUUCCCGACCCUUAGAACCUGACCAGGGUAAUGCCUGCGAAGGGAAGCACGUUUUAUUGAGU
.....(((((((((..(((((..))))).....((((((..))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5791
UCAAAGUGCUAGGGGAGCCAGAAAUGGCUGAGAGGGGAUUCGUUCCCGACCCUUAGAACCUGACCAGGGUAAUGCCUGCGAAGGGAAGCACGUUUUACGGAAU
.....(((((((((..(((((..))))).....((((((..))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5792
UAUGUCCGCUGGGGGAGCCUGAAAAGGCUGAGACGGCAGAAAUGCCGAACCCUUGGAACCUGAUGAGGGUAAUGCCUCCGUAGGGAAUGCGGGCUCAAAAGGCA
.....(((((((((..(((((..))))).....((((((..))))))..)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5793
UAUUUCACAAAGGAGUGCUUUGGCUGAGAUCGCAAUUGCGAAAUCCUGAGGACCUGAUCUUGUUAGUACAAGCGUAGGGAUUGUGACCAAUAAUCAA
.....(((((((((...(((.))).....(((((())))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5794
UUUAACCACUGGAAGUGCCUUUGUUUAAGGCUGAGAGUAAAGAACUGACUUUAUAAUUCCUGGAACCUGAUCCAGUUCAUACUGGCGUAGGGAAGUGGCGACGCUCAAUU
.....(((((((((..(((((.....))))).....((((((......))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5795
AUAGUCUGCUGGGGGAGUUCUUGGGAACUGAGACGGGCAACGCCCGAACCCUUUGAACCUGAUCCGGUUUAUACCGGCGUAGGGAAGCGGCCAGAAACAAUC
.....(((((((((..(((((..))))).....((((((.))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5796
GGGGCAGGCUAGGGGUGCCCGAAUGGAAGGGCUGAGAGCUGGGUUUCUCCCAGCAACCCUUGGAACCUGAUCCGGGUAAUGCCGGCGGAGGGAAGCCUAUGCGGAAGACC
.....(((((((((..(((((......))))).....((((((.....))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5797
ACCAUUCACCAGGGGUGCCCCGGCAAGGGGCUGAGAUUCUGCUGAACAAUACGGCUUUGCCUGUUGUGGCGCGGUGACCCGUUGAACCUGAUCCAGUUCAUACUGGCGUAGGGACGGUGCGGACCUGCGGCU
.....(((((((((..(((((.....))))).....((((((...........................))))))..)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5798
GCGCAUUCCGAGGGGAGCACUAGACGGUGCUGAGAUGGCGUUGAGCCGGACCCUUGAACCUGAUCCGGGUCAUGCCGGCGUAGGAACGGAAAGAAGGCCGCCA
.....(((((((((..(((((....))))).....((((((.))))))..))))....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5799
CGUUACCACAGGGGGGGCUUCUUAGCUGAGAUUGAGUCCACGUGUUUUUGGAUUCUGACCCUUUGAACCUGUUCGUUAAUACGAGCGUAGGGAUUGUGGCGAUUGCAUUUC
.....(((((((((..((((())))).....((((((..............)))))).)))).....((((..(.......))....)))....)))))............
>Name: bpRNA_RFAM_5800
UAAAAUUGCUAGGGGCGCCUUUUGGCUGAGAUAGUUUGACUAGACCCUUAUAACCUGAUUUGGUUCGUACCAACGUAGGAAAGUAGUAUAUUCAGAAU
.....(((((((((..((((())))).......((((.))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5801
ACCUUCACAAAGGGGAGCCAUUGGCUGAGAACGGGGAAACCCGGACCCUUCGAACCUGUUCGUUAAUGCGAGCGUAGGGAUUUGUGAAUGGU
.....(((((((((..(((().))).....((((((..))))))..))))....((((..(.......))....)))....)))))......
>Name: bpRNA_RFAM_5802
ACAUGGCAUCGAUGGACUGGGUUCGUUCUGAGAUUAUACGGCUAAAACUUGAUCUGGAUAAUACCAGCGAAAAGGGUCAUGCCUUCUCUCGUUC
.....(((((((((..(((((..)))))..........)))).....((((..((((......))))...))))...)))))............
>Name: bpRNA_RFAM_5803
AAGUUGCACCAGGGGUGCCUGUAUUCUCAACAAUCUGAAGGGCCCUUGGCCUGGAUUGUUGUGAUAUGGGCUGAGAAAGUCCCUUUGAACCUGAACAGGAUAAUGCCUGCGUAGGGAGUGUGCAUUUCUAUUUUG
.....(((((((((..(((((.............................................))))).........)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5804
GGUUCCUGUCAGGGGAGUCUCGCCAGAGAGACUGAGAGGCUGAUAGCGAUUUUCGCGGCUUAGCGACCCUUAGAACCUGACCCAGCUGAUACUGGCGUAGGAAGACUCGUAUCUUGAUAA
.....(((((((((..(((((......))))).....(.((((................)))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5805
UAGUAUCAUUAGGGGUGCAAUUCAAUUUGCUGAGAGAAAGUCUACUUUCAACCCUUGAACCUGUUGGUUAGCACCAGCGUAGGAAAGUGAGCAAUAUUGAUA
.....(((((((((..(((((....))))).....((((((..))))))..))))....((((..((......))))..))....)))))............
>Name: bpRNA_RFAM_5806
AUUUGCUACUAGGGGAGCCAAAAGGCUGAGAUGAAUGUAUUCAGACCCUUAUAACCUGAUUUGGUUAAUACCAACGUAGGAAAGUAGUUAUUAACUAUU
.....(((((((((..((((())))).....(((((())))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5807
GGAAAGCACUAGGGGUGCUGUUUUGGCUGAGAUAAAGCGCGGAAGAAACGCGCUUUGAUCCCUUAUGACCCGAUCUGGAUAAUACCAGCGUGGGGAAGUGCAGGUUGACCGAA
.....(((((((((..(((((.))))).....((((((.............))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5808
UGUUAGGAGGUGGGGUGCCUGUAUUCUCAACGAUCUGAAGGCCUCUUGGCCUGGAUUGUUGUGAAUUGGGCUGAGAAAGUCCCUUUGAACCUGAACAGGAUAAUGCCUGCGAAGGGAGUGUGCAUUUCUACUUUU
.....(((((((((..(((((.............................................))))).........)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5809
UUGAAUGACUCGGGGUGCCCCUUUUCACAAAGGGCUGAGAAAUACCCGUACCACCUGAUCUGGAUAAUGCCAGCGUAGGGAAGUCAGAUGCCUGCCCG
.....(((((((((..(((((.........))))).........)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5810
CUAUGUUAGGAGGUGGCCUCUUGGCCUGGAUUGUUGUGAAUUGGGCUGAGAAAGUCCCUUUGAACCUGAACAGGAUAAUGCCUGCGAAGGGAGUGUGCAUUUCUACUUUU
.....(((((((((..(((((....................))))).........)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5811
UUUAACCACUAGGGGUGUCCUUCAUAAGGGCUGAGAUAAAAGUGUGACUUUUAGACCCUCAUAACUUGAACAGGUUCAGACCUGCGUAGGGAAGUGGAGCGGUAUUUGU
.....(((((((((..(((((.....))))).....((((((.....))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5812
GAUUCAUCCUAGGGGUGCUUUGCGAAGCUGAGAGAGACUUUGUCUCAACCCUUUUGACCUGAUCUGGAUCAUGCCAGCGGAGGGAAGCGGUGAAAAGCGGAG
.....(((((((((..(((((..))))).....((((((.))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5813
GAUGACCACAAGGGGAGCAUUAAAGCUGAGAGUGAGCGGUUUCGUUCUGACCCUUUGAACCUGUUAGUUAACGCUGGCGUAGGGAUGUGGCAAAGUCAAAUG
.....(((((((((..((((())))).....((((((.....))))))..)))).....((((..((......))))..))....)))))............
>Name: bpRNA_RFAM_5814
CUGGUGUGGUGGGGGAGCUCCAUAAGGGGCUGAGAGGAUCCGGAUGGAUCGAUCCCUGGAACCUGAUCCGGGUAAUACCGGCGGAGGGAAAUUAUGGAAAAAAAUAG
.....(((((((((..(((((....))))).....(.((((....)))))...))))....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5815
AACUAGGCGAGGGGGAGCUCCAUAAGGGGGCUGAGAGGAUCCGGAUGGAUCGACCCCUGGAACCUGAUCCGGGUAAUACCGGCGGAGGGAAUCGUAUGAUGAAUGAGA
.....(((((((((..(((((.....))))).....((((((....)))))).)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5816
AAAAAACCACGCGGGAGCACACACCAAGUGCGCUGAGAGGACGGAUCGGGGCCGUCGACCGUAUGAACCUGACCGGGUAAUGCCGGCGUAGGGAGAUGAAUAAUGACUGAAA
.....(((((((((..(((((.......))))).....(.((((.......)))))..)))).....((((.((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5817
ACUUCAGUACACGGGAGUCCCCAGGCAGUCCGAAUCUGCGGGGCUGAGAGUGGGCACAGCCAGAGUGACUGAACCUACCCUUACCCUCCCACACCUGAUCCGGGUCAUGCCGGCGAAGGGAGGUUCAAGAUGCCGUCAG
.....(((((((((..(((((..................))))).....((((((.....................)))))).))))......((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5818
GCUGCUCUAACGGGGUGCCCUGGCCGGCUUUGCGACCAUGGCUGAGAGGCUUCGAGCCAACCCGCGGAACCUGAUCCGGCUCAUACCGGCGGAGGGAUUAGAAGCGAUCGGACC
.....(((((((((..(((((................))))).......((((.))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5819
AAGAAAAACUAGGGGGGCCGAUUCUGGCUGAGAUAGGAAGGUAAUGCUUUCUGACCCUUUGAACCUGUUUGUUAGUGCAAGCGUAGGGAAGUGAAUGUGAAAGUGA
.....(((((((((..(((((..))))).....((((((........)))))).)))).....((((..((......))))..))....)))))............
>Name: bpRNA_RFAM_5820
CGUUACCACAGGGGGGGCUUCUUAGCUGAGAUUGAAUCCGCGUGUUUUUGGAUUCUGACCCUUUGAACCUGUUCGUUAAUACGAGCGUAGGGAUUGUGGCGAUUGCAUUUC
.....(((((((((..((((())))).....((((((..............))))))..))))....((((..(.......))....)))....)))))............
>Name: bpRNA_RFAM_5821
CCGAACUCAACGGGGUGCCGCGCUCAUGCGCGCGCUGAGAAAAUACCCGUCGAACCUGAUCCGGAUAAUGCCGGCGAAGGGAUUUGAGGCUACCUCUCAA
.....(((((((((..(((((........))).))..........)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5822
CGCAUUCACCAGGGGAGUCCCGGCAAGGGGCUGAGAUACUGCUGGCUUUCGCGGCGCAGUGACCCGUUGAACCUGAUCCAGUUCAUACUGGCGUAGGGACGGUGCAAGCGCUUUGCG
.....(((((((((..(((((.....))))).....((((((.............)))))).)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5823
AAAUACACAAGGGAGUGCCUUGAGCUGAGAUUGCAGAUAUGCAAAAUCCUCUAACCUGAUCUCGUUAGGACGAGCGUAGGAAUUGUGGUUUGAAUUGGU
.....(((((((((..(((().))).....((((((..))))))..))))....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5824
AUAGGACAUUUGGGGUGCGUAACAGCUGAGAUUAUACCCAUUGAACUUGAUACAGUUAGUACUGUCGAAGGGAAAUGUGUGCCAUUACAA
.....(((((((((..((((()))))..........)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5825
UCAUAGCAACUGGGGUGCCAUCACGGCUGAGAUAAUACCCAUUGAACCUGAAUCUGGACAAUGCCAGCGCAGGGAGCAAUGCUUUUAUUUGGGG
.....(((((((((..(((((.)))))..........)))).....((((...((((......))))..))))....)))))............
>Name: bpRNA_RFAM_5826
UUUAAACACUAGGGGUGUCCAAAAAUGGGCUGAGAUGGUGCUGUAAGUACCGAUCCCUUUGAACCUGUAAGCUCAAACUUGCGUAGGAAAGUGUCACAGCUAAUGU
.....(((((((((..(((((....))))).....((((((.....))))))..)))).....((((..((......))))..))....)))))............
>Name: bpRNA_RFAM_5827
CAAGGCACUCGCGGGAGCCCGGACGCACCGGGCUGAGAGGGAGGCUGGCGGCCUCCGACCGUACGAACCUGAUCCGGGUCAUGCCGGCGAAGGGAGGGGCUGGACGCCCAUG
.....(((((((((..(((((.......))))).....((((((......))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5828
AUAUUCCGACAGGGGAGCGCCACAGCGCUGAGAGUGCGGCACCGGCCGCAGACCCUCCGAACCUGGCCCAGGUCAUUCUGGGUAGGGAGAUCGGUCACCACUCGAG
.....(((((((((..(((((..))))).....(.((((......)))))..)))).....((((..((((......)))).))))...)))))............
>Name: bpRNA_RFAM_5829
CCGCCGAAGUGGGGGUACCGCAGCGUGCUGCGGUUGAGAUAGUCCCUUCGAACCUGAUCCGGCUGAUACCGGCGUAGGGAAGCUUCGUCAGAUGCGAU
.....(((((((((..(((((........))))).........)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5830
AAGAACCACUAGGGGAGCCAUCUGGCUGAGAAAAGCGCUGCUUUGACCCUUUGAACCUGAUCUGGCUUGUACCAGCGUAGGGAAGUGGAGAACAAUUGCU
.....(((((((((..((((())))).....((((((.))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5831
UAAUGCUACUAGGGGAGCCAUAGUAAAUGGCUGAGAUGAUUAAUUCAGACCCUUAUAACCUGAUUUGGUUAGUACCAACGUAGGAAAGUAGUUAUGUAAAUGU
.....(((((((((..(((((.....))))).......((((.))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5832
AAACGCUACUAGGGGAGCCAGUUGGCUGAGAUGAUUAAAUUCAGACCCUUACAACCUGAUUUGGUUAAUACCAACGUAGGAAAGUAGUUUAAUCUAAAG
.....(((((((((..((((())))).....(((((())))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5833
GGCAGUCCCCACGGGCGCCCGAGCACGGGCUGAGAUCGCGCUGAUUSUGCGCGAGCACCGUUUGAACCUGUCCGGUUAGCACCGGCGAAGGAAGAGAGGAAUGGUGCAAUG
.....(((((((((..(((((....))))).....((((((........))))))..)))).....((((.((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5834
AGUCCCUGUCAGGGGAGUCUCGCCAGAGAGACUGAGAGGCUAAUAGCGAUUUUCGCGGCUUAGCGACCCUUAGAACCUGACCCAGCUGAUACUGGCGUAGGAAGACUCGUAUCUUGAUGA
.....(((((((((..(((((......))))).....(.((((................)))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5835
CUCCAUUCCGAGGGGAGCGCCGGGCGGCGCUGAGACGGCGGUGAGCCGGACCCUUGAACCUGAUCCGGGUCAUGCCGGCGUAGGAACGGAACGAGGCUGCCCU
.....(((((((((..(((((....))))).....((((((.))))))..))))....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5836
AUCAUCCACUAGGGGGGCCUUUAGAAAGGCUGAGAUCAAAGUGUGCCUUUGAGACCCUUAGCACCUGAUCUGGGUAAUGCCAGCGUAGGGAAGUGGAGGAGCAGCACA
.....(((((((((..(((((....))))).....((((((.....))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5837
AGUGUCCCCCGCGGGCGCCCGAGCACGGGCUGAGAUUGCGCUGAUGCUGUGCAAGCACCGUUUGAACCUGUCUGGUUAACACCAGCGAAGGAAGAGAGGAGCGCGAGCCUA
.....(((((((((..(((((....))))).....((((((.......))))))...)))).....((((.((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5838
UUUAUAAAUCACGGGUGCUGGACGGCAUACGUUUGCCACAAAGCUGAGACAGGGCGAGAAGACGUGCACGUCCCUGAACCGUUGAACCUGAUCCGGGUAAUACCGGCGAUAGGAAGAAUAAUGAACCGAUCG
.....(((((((((..(((((..................))))).....((((((...............))))))..))))....((((..((((......))))...))))..)))))............
>Name: bpRNA_RFAM_5839
ACGAGAUGCCCGGGUGCCAUGUGCUUGCUGUACGUGGCUGAGACGGCUGUUUGGCCGAACCGUAGAACCUGAUCUGGGUAAUACCAGCGAUAGGAAGACUUCAUACUGUGACU
.....(((((.((..(((((.............))))).....((((((..))))))...)).....((((..((((......))))...))))..)))))............
>Name: bpRNA_RFAM_5840
AAAUAUAACUAGGGGUGCUAAGUCAAUUACUUAGCUGAGAUCAUACCCUUCGAACCUGAAACAGUUAAAACUGACGCAGGAAAGUUUCAAUUUGAUCGA
.....(((((((((..(((((.........)))))..........)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5841
GCAAAACACUAGGGGUGCCAUUCAGCAAUCGCUGAGUGGCUGAGAUCACACCCUCCGAACCUGAUACGGGUUGUGCCGGCGCAGGGAAGUGAAAUGACGUGAUC
.....(((((((((..(((((..............)))))..........)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5842
AAACACCACUAGGGGUGCCUCGAUCGGUUUUCUGGUCGACGGGGCUGAGAUCACACCCUCUGAACCUGACCCGGGUCAUGCCGGCGAAGGGAAGUGACCAGCGUGAUCG
.....(((((((((..(((((...................)))))..........)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5843
ACUUUCUUGUCGGAGUGCCUAGCGUAAGCUGUUUUAUCGCAGCAUACACAGGCUGAGACCGUUAAUUCGGGAUCCGCGGAACCUGAUCGGGUUAAUACCCGCGAAGGGAACAAGAGUAAUCAACCG
.....(((((((((..(((((...........................))))).....(((((())))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5844
GCCAUCUCAACGGGGUGCUGGCUGUUUAAAACAGCCUUGCUGAGAGUAAACCCGCCGAACCUGAUCCGGCUAAUACCGGCGUAGGGAUUUGAGCUGCUAACUAUU
.....(((((((((..(((((..............)))))..........)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5845
GCCCGUUCCGAGGGGGGCUCCGACGAGGAGCUGAGAUACCGCACGCUCGCCGCUUCGCUCCGCGAGGCACAGAGACCGCGGUGACCCUUUGAACCUGAUCCGGGUCAUGCCGGCGAAGGGACAGGGAUGCAUCAGACAG
.....(((((((((..(((((.....))))).....((((((...................................)))))).)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5846
AGGAUCACGCAGGGGUACUCGCUGUCCCGCCUUCAAGGCCGGCAGCGUGUUGAGAGAGUCCCUUCGUACCAGUACGGAUAAUGCCGAUGCUGGGAGCGUAUUCCAGUUGCCG
.....(((((((((..(((((........................))))).........)))).....((((.((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5847
CCCUGUAGACACGGGAGUCCCGGGAGCGGGGUCUGAGAGUGGGCGCGCCUGCCCUUACCGUCACACCUGAUCCGGAUCAUGCCGGCGAAGGGAGGUCAAGGAUGGCGUCCG
.....(((((((((..(((((.......))))).....((((((......)))))).))))....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5848
GGGUACCCACGCGGGAGCGCACGCCGAGUGCGCUGAGAGGACGGCUCGGGGCCGUCGACCGUACGAACCUGACCGGGUAAUGCCGGCGUAGGGAGUUGCAAAUGACCAUCA
.....(((((((((..(((((.......))))).....(.((((.......)))))..)))).....((((.((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5849
ACCUGACGCUAGGGGUGUUGGUGAAUUCACCGACUGAGAAUAACCCUUUGAACCUGAUAGAGAUAAUGCUCGCGCAGGGAAGCAAGAAUAGAAAGAU
.....(((((((((..(((((........))))).........)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5850
AUACUAGGCACGGGGUGCCAACCGGAUGGAAAAAUUCCGGAGGCUGAGAAAACACCCGUUGAACCUGCUCUAGCUCGUACUAGCGAAGGGAUGGCCUUAACGUGGCUA
.....(((((((((..(((((..................)))))..........)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5851
GUUUUCCACUAGGGGAGUCCUUGAUAAGGGCUGAGAUAAAAGUUUGACUUUUAGACCCUCAUAACCUGAACAGGUUCAAACCUGCGUAGGGAAGUGGCACGGUAUUUGA
.....(((((((((..(((((.....))))).....((((((.....))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5852
CCGCCGAAGUGGGGGUACCACAGCACUGCUGCGGUUGAGAUAGUCCCUUCGAACCUGAUCCGGCUCAUACCGGCGUAGGGAAGCUUCGUUAGAUGCGCU
.....(((((((((..(((((.........))))).........)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5853
GCGUUCUUGUCGGGGUGCCUUGCUGUGAGGCUGAGAUCGGUUAAACCGGAUCCCGUUGAACCUGAUCAGGUUAGCGCCUGCGUAGGGAACAAGAUUUCUCGUCUC
.....(((((((((..(((((.....))))).....((((((.))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5854
CGGUUCUUGUCGGGGUGCCUUGCUAUGAGGCUGAGAUCGGAUAAUCCGGAUCCCGUUGAACCUGAUCAGGUUAGCGCCUGCGUAGGGAACAAGAUUUCUCGUCAC
.....(((((((((..(((((.....))))).....((((((.))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5855
AUAGGACAUUUGGGGUGCGUAACAGCUGAGAUUAUACCCAUUGAACUUGAUGCAGUUAGUACUGUCGAAGGGAAAUGUGUGCCAUUACAA
.....(((((((((..((((()))))..........)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5856
AACGGCCACUGGGGGUGCCGGUCAAAACCGGCUGAGAGGGAGAGUUCUCCCAACCCUUUGAACCUGAUCCGGGUAAUACCGGCGUAGGGAAAGUGGGGUAACUGGAAG
.....(((((((((..(((((......))))).....((((((..))))))..)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5857
UAUUUGCACAAUGGGUCUAUUGACAAGUCUGUCAGUAGCGAGAAAUACCAUCUGACCUGAUCUGGGUAAUGCCAGCGUAGGAAUGUGUUAAGACAAUCGU
.....(((((((((..(((((............))))).........))))....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5858
CUCAUACACUUGGGGAGCCUCGCACGAGGCUGAGAGGUGCCGGGCACCGACCCAUCGAACCUGAUCCGGGUCAUGCCGGCGUAGGGAAGGGUAGAGUGAAGCGG
.....(((((((((..(((((....))))).....((((((.))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5859
CAAAUAUAGUCGGGGGGCCUGAAGGCUGAGAUCGCAUAGUGCGAAACCCGUUGAACCUGAUUCAGUUAAUACUGGCGUAGGGAACUAUAAGUCUUGUUUU
.....(((((((((..((((())))).....((((((.))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5860
GACAUCCACUAGGGGGGCCUUUAGAAAGGCUGAGAUCAAAGUGUGCCUUUGAGACCCUUAGCACCUGAUCUGGGUAAUACCAGCGUAGGGAAGUGGAGAGGAGCUACA
.....(((((((((..(((((....))))).....((((((.....))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5861
UCAUCACGCUAGGGGUGCCAUUGUGGCUGAGAAAGAGACUUAAGUCUCUUAACCCUUUGAACCUGAUGCGGUUAGUACCGCCGGAGGGAAGCGGAAAAUAUUGUUU
.....(((((((((..(((((.))))).....((((((......))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5862
AGAAAACCCGAGGGGAGCUCCAUAAGCCGGGGCUGAGAGGAAGGCGGAAGUCUUCGACCCUUAGAACCUGAACCGGGUAAUACCGGCGGAGGGACGGGUAGAGAAAAUUUC
.....(((((((((..(((((.......))))).....(.((((......)))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5863
UCUAUCCACUAGGGGUGCCGAUAUUGGCUGAGAUUAAAGUUUAUCUUUGAGACCCUUAGUACCUGAUCUGGUUCGUACCAGCGUAGGGAAGUGGAAAUGACAAAAU
.....(((((((((..(((((..))))).....((((((.....))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5864
UAAUGCCUGGAGGGGAGCUCCAAAAUGCGGGGCUGAGAGGAAGGAGUCAAUCCUUCGACCCUUCGAACCUGAUCCGGGUAAUACCGGCGGAGGGACCAGGUGACUCAAAAAU
.....(((((((((..(((((.......))))).....(.((((.......)))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5865
CAACAACCGUUGGGGUGCCCGAUUCAGGGCUGAGAGGCGCACUGUGCCGACCCAUGGAACCUGAUCCGGGCAAUACCGGCGUAGGGAACGGUCAUCGUGGCAAU
.....(((((((((..(((((....))))).....((((((.))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5866
UACAGUCUGAGAGGAAGUGUUAAACUUCGACCGCACCUGAUCUGGGUAAUGCCAGCGGAGGGAACGAUACUUAGUCUAAU
.....(((((((((..(((().))).....)))).((((..((((......))))..))))...)))))...........
>Name: bpRNA_RFAM_5867
UAAAGACAUUUGGGGUGCUUUAGGCUGAGAUGAUACCCAUUGAACCUGAUACAGUUAAGACUGGCGAAGGGAAAUGUGAAAUGUUUUUU
.....(((((((((..(((().)))..........)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5868
UAGAGACAUUUGGGGUGCUUUAAGCUGAGAUGAUACCCAUUGAACCUGAUACAGUUAAGACUGGCGAAGGGAAAUGUGAAACGUUUUUU
.....(((((((((..(((().)))..........)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5869
CAAAAUUCGUUGGGGUGCCUUGAAAGAGGCUGAGAGACGCAUUCUCACGUCAACCCAUUGAACCUGAUCCGGGUAAUACCUGCGUAGGGAACGGAGUUUGGCGCGUC
.....(((((((((..(((((....))))).....((((((....))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5870
UCAAACUACUAGGGGUGCCCGGAUUUGGCGGGCUGAGAGAAAAACCGGCGUUUUUCAACCCUUUGGACCUGAUCCGGAUCAUACCGGCGUAGGAAAGUAGGAAUUUGUAAAA
.....(((((((((..(((((.......))))).....((((((......))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5871
AUGUUCUUGUCGGGGUGCCUUGAAGCAAAGGCUGAGAUCGCAAAGUUGCGGAUCCCGUUGAACCUGAUCAGGUUAGCGCCUGCGUAGGGAACAAGAUUGCUCUCAUU
.....(((((((((..(((((......))))).....((((((..))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5872
GCCAUCUUGUCGGAGUGCCAACCGUCGAACGACGCGAGGCUGAGACCGUUAAUUCGGGAUCCGUGGAACCUGAUCAGGCUAGCACCUGCGAAGGGAAACAAGGGUAACUUGCGG
.....(((((((((..(((((..............))))).....(((((())))))..)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5873
GUGUACAUCAAUGUCAAGAAGAGGAGAGCGUGGCUGAGAUUAUACGGCGAAACUUGAUCUGGAUAAUACCAGCGAAAGGAUCAUGCUCUCCUCCCCC
.....((((((.(((((............)))))..........).......((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5874
UUUAACCACUAGGGGUGUCCUUCAUAAGGGCUGAGAUAAAAGUGUGACUUUUAGACCCUCAUAACUUGAACAGGUUCAGACCUGCGUAGGGAAGUGGAGCGUAUUUGUG
.....(((((((((..(((((.....))))).....((((((.....))))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5875
UAGUUCCACUAGGGGUGUCAGUUUGUCUGACUGAGAGAGGGAAGCCUCAACUCUUAAAACCUGAUCUAGCUUGUACUAGCGUAGGGAAGUGGUGGCACAUUCUA
.....(((((((((..(((((.....))))).....(((((())))))..)))).....((((..((((......))))..))))..)))))............
>Name: bpRNA_RFAM_5876
AAAAAACUAUUAGGGUGCCCGUAGUAUGGGUUUAGAAAAAACCUUUUGGACUUGAUAUGGAUCAUACCAGCUUAGGAAAGUAGUGUAAUUUUUUCC
.....(((((((((..(((((.....)))))..........)))).....((((..((((......))))..))))...)))))............
>Name: bpRNA_RFAM_5877
GAUGACCACAAGGGGAGCAUUAAAGCUGAGAGUGAGCGGUUUCGUUCUGACCCUUUGAACCUGUUAGUUAACGCUGGCGUAGGGAUGUGGCAAAUGCAAUAG
.....(((((((((..((((())))).....[(.(((......))))...)))).....((((..((......))))..))]...)))))............
>Name: bpRNA_RFAM_5878
AAUAGUUACUGGGGGUGCCCGCUUUCGGGCUGAGAGAGAAGGCAAGCUUCUUAACCCUUUGGACCUGAUCUGGUUCGUACCAGCGUGGGGAAGUAGAGGAAUUGUUUU
.....(((((((((..(((((....))))).....((((((.....))))))..)))).....((((..((((......))))..))))..)))))............
